version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes: 
      - type: bind
        source: ./frontend
        target: /app
      - type: volume
        target: /app/node_modules
    ports:
      - 3000:3000
    environment: 
      #solution stackoverflow, pour le hot reload
      - CHOKIDAR_USEPOLLING=true
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - type: bind
        source: ./backend
        target: /app
      - type: volume
        target: /app/node_modules
    ports:
      - 5000:80
  reverse-proxy:
    build: 
      context: ./reverse-proxy
      dockerfile: Dockerfile.dev
    ports:
      - 80:80
    depends_on:
      - backend

