version: '3.8'
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - 5000:80
  reverse-proxy:
    build: 
      context: ./reverse-proxy
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
      - 443:443
    #pour acceder aux certificat ssl sur la machine hote
    volumes:
      - type: bind
        source: /etc/letsencrypt
        target: /etc/letsencrypt
